### ISSUE TITLE
What does the 'srf' mean in your code

### ISSUE THREAD

**Issue by wxywhu** [aicip/uSDN#1]
Hi, I want to know what the 'srf' means in your code, why its dimension is 3*31 and how to obtain the value in it. Similarly, I could not find the corresponding explanation in the paper.

**Comment by yingutk** [comment]
That is the transformation matrix in equation (2) of the paper.

**Comment by wxywhu** [comment]
@yingutk Thank you so much~ If 'srf' donate the transformation matrix, why does the function encoder_uniform_hsi generate 'layer1' to produce uniform?  Besides, it seems each layer in the HSI network contains three nodes(nLRlevel=3), inconsistent with the paper.

**Comment by yingutk** [comment]
We optimize the parameter settings, 3 nodes are enough to generate representations.

**Comment by wxywhu** [comment]
So why does the function encoder_uniform_hsi generate 'layer1' to produce uniform? In the function encoder_uniform_hsi:  layer_1 = tf.matmul(x, self.input.srf.T). Does this mean you transform the input lr_hsi to lr_msi ?

**Comment by yingutk** [comment]
> So why does the function encoder_uniform_hsi generate 'layer1' to produce uniform? In the function encoder_uniform_hsi: layer_1 = tf.matmul(x, self.input.srf.T). Does this mean you transform the input lr_hsi to lr_msi ?

You don't have to generate layer1, but with layer1, the results are more stable.
